baseurl = "http://dam.jongbin.com/"
title = "아빠와 나"
# Enable comments by entering your Disqus shortname
disqusShortname = "daddyandme"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-88094548-2"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"

# Language settings
languageCode = "ko-KR"
hasCJKLanguage = true

[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    # Tell me who you are
    author = "정종빈"
    bio = "주말아빠"
    location = "우리집"
    site_description = "아빠와 딸이 열심히 놀러 다니는 이야기"
    copyright  = "[종빈](http://jongbin.com) + \
                  [휴고](//gohugo.io) 블로그 + \
                  [Icarus](http://github.com/ppoffice) 테마"
    avatar = "media/avatar.png"
    logo = "css/images/logo.png"
    disable_mathjax = true # set to true to disable MathJax

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
    custom_css = [
    "css/noto.css"
    ]
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "홈"
    link   = "/"

#[[params.menu]]
    #before = false
    #label  = "태그"
    #link   = "tags/"

#[[params.menu]]
    #before = false
    #label  = "분류"
    #link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/jongbinjung"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "jongbinjung"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = "bean8636"
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = false
    tags = true
    tag_cloud = true
